image:
  repository: ghcr.io/mlflow/mlflow
  tag: "v3.11.1-full"

replicaCount: 1

server:
  flag_options:
    - serve_artifacts
  value_options:
    host: "0.0.0.0"
    workers: 2
    allowed_hosts: "*"
    cors_allowed_origins: "*"

mlflow:
  backendStoreUri: "postgresql://mlflow:mlflow123@mlflow-postgres-postgresql.mlflow.svc.cluster.local:5432/mlflow"
  artifactsDestination: "s3://churn-mlflow-artifact"

service:
  type: ClusterIP

env:
  - name: MLFLOW_ENABLE_PROXY_MULTIPART_UPLOAD
    value: "true"
